### ISSUE TITLE
Call to group fails via SIP

### ISSUE THREAD

**Issue by an0key** [emfcamp/numbermanagement#17]
Line 1 - 6666 (making the call) - SIP

Calling - Group 5853. That has a member 5060 (SIP).

Line 1 gets a busy signal when calling 5853 (Group). Can call 5060 directly no issue.

**Comment by sammachin** [comment]
I don't think this was due to the change number type now. 
I found a bug in the API groups code for join/leave that was triggering a remove of the group number from jambonz instead of just clearing the cache. The API is what gets calls when a user updates a group member via IVR.
This was fixed by [#e94b709b5671a2cde36a97c89b2f7259ed88e22a](https://github.com/emfcamp/numbermanagement/commit/e94b709b5671a2cde36a97c89b2f7259ed88e22a) 
Also I made the IVR join/leave call flow more robust as it was failing on certain cases like joining via IVR if the group wasn't cached.

**Comment by sammachin** [comment]
Also fixed in https://github.com/emfcamp/numbermanagement/commit/bf1daeb4938d2e259e33b1c297a78b7f2339b0eb which was trigger a full remove not just a cache invalidation when number details were updated, this would be affecting App numbers too
