### ISSUE TITLE
Cannot add jambonz number to group

### ISSUE THREAD

**Issue by aveao** [emfcamp/numbermanagement#20]
As described in the title, I cannot find my jambonz number in the list of numbers I can add to my group. There seems to be nowhere where it says that this shouldn't be possible, so I think either more documentation is needed, or support to add jambonz numbers to groups should be added.

(Trying curl shenanigans to force adding a jambonz number to a group leads to a HTTP 500.)

---

edit:

I see that there's code to check if a number is group capable, but other bits of code say that trying to add one should lead to a 400 with a verbose error, not 500, and I see nowhere where group capable is set to false for jambonz numbers:

https://github.com/emfcamp/numbermanagement/blob/141d7a6320dda643bedbd7862fbf0fb96e29b620/groups/forms.py#L15

---

edit 2: 

I don't see jambonz here, so I'm guessing it was added separately, but marked as not group_capable. Is this intended?

https://github.com/emfcamp/numbermanagement/blob/main/fixture.json

**Comment by sammachin** [comment]
Yes an App number would be non group-capable as apps will generally answer immediatly so there wouldn't be much point putting it in a group with other numbers, also the routing for Group to app is tricky as Groups are actually an app themselves.

FYI the fixture.json is just some test data rather than actual config, Types Of Service are created dynamically when the system is setup so don't take that data as too important.

Docs are coming shortly, I just need to write the section about Groups!
